# Generated by Django 4.2.3 on 2023-07-25 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('hugo_dir', models.CharField(blank=True, max_length=1024)),
                ('data_dir', models.CharField(blank=True, max_length=1024)),
                ('setup_github', models.BooleanField(default=True)),
                ('github_repo_url', models.CharField(blank=True, max_length=1024)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('markdown_file', models.FileField(blank=True, upload_to='markdown_files/')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artgen.website')),
            ],
        ),
    ]
