# Generated by Django 4.2.3 on 2023-07-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('site', models.CharField(choices=[('site1', 'Site 1'), ('site2', 'Site 2')], max_length=20)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
