# Generated by Django 4.2.3 on 2023-07-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='setup_github',
            field=models.BooleanField(default=True),
        ),
    ]
