# Generated by Django 4.2.3 on 2023-08-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgen', '0002_article_failed_flag_alter_website_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='author_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='website',
            name='google_analytics',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='website',
            name='title',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
