# Generated by Django 4.2.3 on 2023-08-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artgen', '0003_website_author_name_website_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='website',
            name='name',
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField()),
                ('previous_position', models.PositiveIntegerField()),
                ('search_volume', models.PositiveIntegerField()),
                ('keyword_difficulty', models.PositiveIntegerField()),
                ('cpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.URLField()),
                ('traffic', models.PositiveIntegerField()),
                ('traffic_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('traffic_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('competition', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_results', models.PositiveIntegerField()),
                ('trends', models.JSONField()),
                ('timestamp', models.DateTimeField()),
                ('serp_features', models.TextField()),
                ('keyword_intents', models.CharField(max_length=255)),
                ('position_type', models.CharField(max_length=255)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artgen.competitor')),
            ],
            options={
                'unique_together': {('competitor', 'keyword', 'timestamp')},
            },
        ),
    ]
